### PR TITLE
Adding generic XMLs

### PR DESCRIPTION
**Pull request by briannen**
Adding the new generic XMLs.

### CODE REVIEW

**Comment by willmayfield** [comment]
@VanderleiVargas-NOAA

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by briannen** [comment]
The run scripts have now all been tested!

**Comment by willmayfield** [comment]
Great, thank you for testing them!!

**Review by willmayfield — APPROVED** [review]
I think they're probably ready to merge now!

**Pull request merged**
