### PR TITLE
Adding XML files

### PR DESCRIPTION
**Pull request by CPKalb**
THIS REPOSITORY IS NOW DEPRECATED; NEW PULL REQUESTS WILL BE CLOSED

For information about transitioning your changes from the regional_workflow repository to the merged UFS SRW App repository, see documentation in the UFS SRW Wiki: 

https://github.com/ufs-community/ufs-srweather-app/wiki

### CODE REVIEW

**Review by michelleharrold — APPROVED** [review]
I think these look good! Only 2 comments: 1) potentially remove the .DS_Store files that occasionally pop up? I am not 100% certain what they are, so maybe they need to be there!, and 2) Not sure if we would want ensemble mean bias plots?

**Comment by JeffBeck-NOAA** [comment]
> I think these look good! Only 2 comments: 1) potentially remove the .DS_Store files that occasionally pop up? I am not 100% certain what they are, so maybe they need to be there!, and 2) Not sure if we would want ensemble mean bias plots?

Those .DS_Store files are from MacOS and are created for each folder opened by "Finder".  It's possible they were added to commits in this PR through "git add -A", which adds all files in a directory.  It should be easy to push a new commit after they're removed locally.  

I think having ensemble mean bias plots is worthwhile.

**Review by JeffBeck-NOAA — COMMENTED** [review]
Can we add ensemble mean lines to the individual member bias plots?  @michelleharrold, is that what you were thinking?  Are we interested in ROC plots, or did we decide that AUC is sufficient?

**Comment by briannen** [comment]
I agree about the DS_store files, but other than that, I think they look good!

**Comment by CPKalb** [comment]
Am I adding these bias plots?  

I did add the files from a mac, so I'm assuming that's where the server files came from.  I am new to mac, so didn't realize this would happen.  I'll delete them.

**Comment by michelleharrold** [comment]
@JeffBeck-NOAA and @CPKalb -- I do think for continuous fields, having the ensemble mean bias is nice (but I know if would be extra work, so take my suggestion with a grain of salt!). We have made plots with just the ensemble mean and we have also put the ensemble mean on the bias by member plots as well...pros/cons to both. They can get lost in all the lines on the individual member plots, but it is then one less plot to have to make and digest. I would lean toward putting them on the bias by member plots.

**Comment by JeffBeck-NOAA** [comment]
> I would lean toward putting them on the bias by member plots.

Agreed!

**Review by willmayfield — APPROVED** [review]

**Review by JeffBeck-NOAA — COMMENTED** [review]
Thanks, @CPKalb, for getting the ensemble mean added!

**Pull request merged**
